### ISSUE TITLE
Keybindings are broken in MacOS Mojave

### ISSUE THREAD

**Issue by vicmarcal** [microsoft/vscode-notepadplusplus-keybindings#10]
Hi!
MacOS Mojave 10.14.3
After enabling Notepad++ Keybindings, I'm having several issues with simple commands.
- The "Option" button to print alternative symbols stops working.
- Command + C and Command + V are not working either. Even more, there are "odd shortcuts" attached to them, as you can see in the following image:
<img width="706" alt="image" src="https://user-images.githubusercontent.com/6674048/52973104-4c183080-33bd-11e9-9651-93ad203323d2.png">
As soon as I disable the Notepad++ Keybindings plugin, and as long as I keep it disabled, the issue disappears:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/6674048/52973258-bdf07a00-33bd-11e9-9e47-0ae7697aa85a.png">

**Comment by egamma** [comment]
@vicmarcal can you try whether some of the work arounds from this doc help https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-mac-keybindings
