### ISSUE TITLE
Don't map F10

### ISSUE THREAD

**Issue by ffes** [Microsoft/vscode-notepadplusplus-keybindings#4]
First of all, thanks for this keymap. I really like it and use it every day.

I would suggest not to map the `F10` key.

First of all, in notepad++ full screen is F11.

But I would suggest not to map both those keys, because those keys are the default binding for `Step Over` and `Step Into` in vscode, a feature n++ doesn't have. I use the integrated debugger a lot more (almost daily) then I even used full screen (never).

I know you can call this a personal thing. And I understand if you would close this as "won't fix" because I can override that key (which I did), but at least I want your thought on it ;-)

**Comment by auchenberg** [comment]
@ffes Thanks for the feedback! I've pushed a change so fullscreen is mapped to F11, and the mapping is now disabled when in debug mode so it doesn't collide with debugging.
