### ISSUE TITLE
Active extension make "Alt + S" as a shortcut for "Save as"

### ISSUE THREAD

**Issue by milyl** [microsoft/vscode-notepadplusplus-keybindings#6]
Hi, I have an issue when your extension is on, shortcut "Alt+S" which should give me a special polish character "ś" works like click of Save as -> "Alt+Ctrl+S" 
When extension is disabled, there is no issue.

**Details:**
> Version: 1.27.2 (system setup)
> Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
> Date: 2018-09-12T16:17:45.060Z
> Electron: 2.0.7
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> Architecture: x64

**Comment by auchenberg** [comment]
Hi @milyl 

The shortcut provided by this extension is:

```
            {
                "key": "ctrl+alt+s",
                "command": "workbench.action.files.saveAs"
            },
```

Can you help confirm that it's `ctrl+alt+s` and not `alt+s`?

**Comment by milyl** [comment]
Hi @auchenberg,
I had problem with "alt+s". "had" because now everything is fine. Probably some updates solved a problem.

**Comment by auchenberg** [comment]
Alright, that's good to hear @milyl
